export const department : string = 

`
DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE IF NOT EXISTS DEPARTMENT (

_id SERIAL NOT NULL,
name VARCHAR(150) NOT NULL,
abbreviation VARCHAR(8) NOT NULL,
description VARCHAR(250) DEFAULT 'Not Available',

created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
slug VARCHAR(40) UNIQUE NOT NULL,

faculty_id INT NOT NULL,
user_id INT NOT NULL,
status_id INT NOT NULL,	

CONSTRAINT DEPARTMENT_PKEY PRIMARY KEY(_id)

)

`;