export const emailMessageType : string = 

`
DROP TABLE IF EXISTS EMAIL_MESSAGE_TYPE;
CREATE TABLE IF NOT EXISTS EMAIL_MESSAGE_TYPE (

email_message_type_id SERIAL NOT NULL,
title VARCHAR(100) NOT NULL,
description VARCHAR(300) NOT NULL,

created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

email_message_type_no INT UNIQUE NOT NULL ,
slug VARCHAR(40) UNIQUE NOT NULL,
user_id INT NOT NULL,
status_id INT NOT NULL,

CONSTRAINT EMAIL_MESSAGE_TYPE_PKEY PRIMARY KEY(email_message_type_id)	

)	


`;