export const publisher : string = 

`
DROP TABLE IF EXISTS PUBLISHER;
CREATE TABLE IF NOT EXISTS PUBLISHER (

_id SERIAL NOT NULL,
name VARCHAR(150) NOT NULL,

created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
slug VARCHAR(40) UNIQUE NOT NULL,

user_id INT NOT NULL,
status_id INT NOT NULL,

CONSTRAINT PUBLISHER_PKEY PRIMARY KEY(_id)	

)	


`;