export const role : string = 

`
DROP TABLE IF EXISTS ROLE;
CREATE TABLE IF NOT EXISTS ROLE (

_id SERIAL NOT NULL,
name VARCHAR(150) NOT NULL,
word VARCHAR(20) NOT NULL,
description VARCHAR(250) DEFAULT 'Not Available',

created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
slug VARCHAR(40) UNIQUE NOT NULL,

user_id INT NOT NULL,
status_id INT NOT NULL,

CONSTRAINT ROLE_PKEY PRIMARY KEY(_id)

)	

`;