export const thesisGrade : string = 

`
DROP TABLE IF EXISTS THESIS_GRADE;
CREATE TABLE IF NOT EXISTS THESIS_GRADE (

_id SERIAL NOT NULL,
name VARCHAR(200) NOT NULL,
word VARCHAR(20) NOT NULL,
description VARCHAR(300) NOT NULL,

created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

slug VARCHAR(40) UNIQUE NOT NULL,
user_id INT NOT NULL,
status_id INT NOT NULL,

CONSTRAINT THESIS_GRADE_PKEY PRIMARY KEY(_id)	

)	


`;