export const userSignature : string = 

`
DROP TABLE IF EXISTS USER_SIGNATURE;
CREATE TABLE IF NOT EXISTS USER_SIGNATURE (

_id SERIAL NOT NULL,
location VARCHAR(200) NOT NULL,
mimetype VARCHAR(25) DEFAULT 'Not Available',
size VARCHAR(25) DEFAULT 'Not Available',
key VARCHAR(200) NOT NULL,


created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
slug VARCHAR(40) UNIQUE NOT NULL,

user_id INT UNIQUE NOT NULL,
status_id INT NOT NULL,

CONSTRAINT USER_SIGNATURE_PKEY PRIMARY KEY(_id)	

)	

`;